// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "DialogueprototypingGlobalVariables.generated.h"

UCLASS(BlueprintType)
class UDialogueprototypingTutorialCheckVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="TutorialCheck")
	UArticyBool* TalkingToDude = nullptr;
	
	 UDialogueprototypingTutorialCheckVariables() 
	{
		TalkingToDude = CreateDefaultSubobject<UArticyBool>("TalkingToDude");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		TalkingToDude->Init<UArticyBool>(this, Store, TEXT("TutorialCheck.TalkingToDude"), false);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class UDialogueprototypingGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="TutorialCheck")
	UDialogueprototypingTutorialCheckVariables* TutorialCheck = nullptr;
	
	 UDialogueprototypingGlobalVariables() 
	{
		/** create the namespaces */
		TutorialCheck = CreateDefaultSubobject<UDialogueprototypingTutorialCheckVariables>("TutorialCheck");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		TutorialCheck->Init(this);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UDialogueprototypingGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UDialogueprototypingGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
