// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyDatabase.h"
#include "DialogueprototypingExpressoScripts.h"
#include "DialogueprototypingDatabase.generated.h"

UCLASS(BlueprintType)
class UDialogueprototypingDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UDialogueprototypingDatabase() 
	{
		SetExpressoScriptsClass(UDialogueprototypingExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UDialogueprototypingDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UDialogueprototypingDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UDialogueprototypingGlobalVariables* GetGVs() const override
	{
		return static_cast<UDialogueprototypingGlobalVariables*>(Super::GetGVs());
	}
};
