// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "DialogueprototypingGlobalVariables.h"
#include "DialogueprototypingExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UDialogueprototypingMethodsProvider : public UInterface { GENERATED_BODY() };
class IDialogueprototypingMethodsProvider
{
	GENERATED_BODY()
	
protected:
};

UCLASS(BlueprintType, Blueprintable)
class UDialogueprototypingExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UDialogueprototypingTutorialCheckVariables> TutorialCheck = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UDialogueprototypingGlobalVariables>(GV);
		if(ensure(gv))
		{
			/** Initialize all GV namespace references */
			TutorialCheck = gv->TutorialCheck;
		}
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UDialogueprototypingMethodsProvider::StaticClass();
	}
	
public:
	
	 UDialogueprototypingExpressoScripts() 
	{
	}
};
